spring.application.name=journal
# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=springdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sql@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
